#!/bin/bash

## common - source this file with ". ./ci/common" to set environment
## variables and make useful functions available.

mkdir -p bin
export PATH="$PWD/bin:$PATH"

## NOTE: These are default values for relevant environment variables
##
if [ -z ${KUBE_VERSION:-} ]; then
    ## ref: https://github.com/kubernetes/kubernetes/releases
    ##
    export KUBE_VERSION=1.7.3
fi
if [ -z ${HELM_VERSION:-} ]; then
    ## ref: https://github.com/helm/helm/releases
    ##
    export HELM_VERSION=3.2.0
fi
if [ -z ${K3D_VERSION:-} ]; then
    ## ref: https://github.com/rancher/k3d/releases
    ##
    export K3D_VERSION=1.7.0
fi

## NOTE: The setup_... functions cache downloads but ensure the correct version
##
setup_kubectl () {
    echo "setup kubectl ${KUBE_VERSION}"
    curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    sudo mv ./kubectl /usr/local/bin/kubectl
    kubectl version --client
}

setup_helm () {
    echo "setup helm ${HELM_VERSION}"
    curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | DESIRED_VERSION=v${HELM_VERSION} bash
    helm version --client
}

setup_k3d () {
    echo "setup k3d ${K3D_VERSION}"
    curl -s https://raw.githubusercontent.com/rancher/k3d/master/install.sh | TAG=v${K3D_VERSION} bash
    k3d version
}
