#!/bin/bash
set -eu

# Decrypt the private SSH key having its public key registered as a deployment
# key for github.com/jupyterhub/helm-chart.
openssl aes-256-cbc -K $encrypted_dae848772642_key -iv $encrypted_dae848772642_iv -in ci/publish-id_ed25519.enc -out ci/publish-id_ed25519 -d
chmod 0400 ci/publish-id_ed25519

# Activate logging of bash commands now that the sensitive stuff is done
set -x

# As chartpress use git to push to our Helm chart repository, so we configure
# git ahead of time to use the deployment key.
export GIT_SSH_COMMAND="ssh -i ${PWD}/ci/publish-id_ed25519"

if [ "${TRAVIS_TAG:-}" == "" ]; then
    # Using --long, we are ensured to get a build suffix, which ensures we don't
    # build the same tag twice.
    chartpress --publish-chart --long
else
    # Setting a tag explicitly enforces a rebuild if this tag had already been
    # built and we wanted to override it.
    chartpress --publish-chart --tag "${TRAVIS_TAG}"
fi

# Let us log the changes chartpress did, it should include replacements for
# fields in values.yaml, such as what tag for various images we are using.
git --no-pager diff
