# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
# This workflow test the Helm chart in the following ways:
#
#   1. runs `helm lint`
#   2. runs `helm install` with the `--wait` flag to ensure that pods startup and
#      enters a ready state.
#   3. runs `helm test` that runs primitive tests defined as part of the Helm chart
#      under pebble/templates/tests to verify things seem to work.
#
name: Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
  workflow_dispatch:

jobs:
  test_pebble:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Lint chart
        run: |
          helm lint pebble --values ci/ci-values.yaml
          helm lint pebble --strict --values ci/ci-values.yaml

      # ref: https://github.com/jupyterhub/action-k3s-helm
      - uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-version: ""
          helm-version: ""
          metrics-enabled: false
          traefik-enabled: false

      - name: Validate chart templates
        run: |
          helm template pebble ./pebble --values ci/ci-values.yaml --validate

      - name: Install chart
        run: |
          helm install pebble ./pebble --values ci/ci-values.yaml

      - name: Await install
        uses: jupyterhub/action-k8s-await-workloads@v3
        with:
          workloads: "" # all
          namespace: "" # default
          timeout: 60
          max-restarts: 0

      - name: Test chart
        run: |
          helm test pebble

      # ref: https://github.com/jupyterhub/action-k8s-namespace-report
      - name: Kubernetes namespace report
        uses: jupyterhub/action-k8s-namespace-report@v1
        if: always()
        with:
          # The pebble-test and pebble-coredns-test pods are created by `helm
          # test`, and the other workloads are part of the helm chart itself.
          #
          important-workloads: pebble-test pebble-coredns-test deploy/pebble deploy/pebble-coredns
